service: serverless-example

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

custom:
  serverless-plugin-typescript:
    tsconfigPath: ./tsconfig.build.json